export { default as getAddress } from './getAddress'
export { default as getBalance } from './getBalance'
export { default as getMetadata } from './getMetadata'
export { default as deploy } from './deploy'
export { initiate as sendToEthereum } from './sendToEthereum'
